/* Generated by Huawei IoT Studio */
#define CONFIG_SHELL_ENABLE 1
#define CONFIG_Demo_Helloworld 1
#define CONFIG_USER_DEMO "hello_world_demo"
#define CONFIG_LIBC_ENABLE 1
#define CONFIG_OS_LiteOS 1
#define CONFIG_ARMV7_M 1
#define CONFIG_OS_TYPE "liteos"
#define CONFIG_ARCH_CPU_TYPE "armv7-m"
#define CONFIG_TCPIP_TYPE "none"
#define CONFIG_DTLS_TYPE "none"
#define CONFIG_EMBEDTLS_MODE "none"
#define CONFIG_LWM2M_TYPE "none"
#define CONFIG_MQTT_TYPE "none"
#define CONFIG_OC_LWM2M_TYPE "none"
#define CONFIG_OC_MQTT_TYPE "none"
#define CONFIG_OC_LWM2M_DEMO_TYPE "none"
#define CONFIG_OC_MQTT_DEMO_TYPE "none"
